name: ZZ Diagnostic
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
